### ISSUE TITLE
Installation Description

### ISSUE THREAD

**Issue by rtubio** [satnet-project/protocol#6]
Document how to install and configure the protocol in a machine now that it has to be executed by supervisord.

**Comment by sgongar** [comment]
The supervisord basic usage is documented now. A more detailed explanation will be created if it's needed by the users.

**Comment by rtubio** [comment]
@sgongar, I have one doubt about the documentation about how to launch this component: why do you say that it is necessary to activate the virtual environment prior to launching the protocol software? Does not supervisord activate that environment by itself?

Also, could you describe better how to install this component so that supervisord launches it? Or does the Bash setup script already configure everything so that you do not have to do anything at all?
