### ISSUE TITLE
Configuration file and .tac

### ISSUE THREAD

**Issue by rtubio** [satnet-project/protocol#9]
It looks like server_amp.py reads the external configuration file and gets the runtime data out of that place; however, the init.d script executes the .tac file which is generated by setup.sh:

1) please, move the .tac file out of the bash setup file,
2) make it load the configuration from the .settings file on the root folder;

Is there any reason why you cannot use the .tac file from the root of the folder instead of creating it with bash?

**Comment by sgongar** [comment]
Problem is now fixed. The .tac configuration file is reading the parameters from an external file called '.settings'.
